### ISSUE TITLE
New name for the app

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ThinkDigitalSoftware/tavern#9]
We need a new name for the app, 

1. It sounds too plain
2. There's already a [pub_client](https://github.com/jimsimon/pub_client.git) library, which is really close. (We'll actually be depending on it)

**Comment by GroovinChip** [comment]
Could we not just call it `pub.dev`? Alternatively:
- Dart Packages Explorer
- Flutter Packages Explorer (not the best because it singles out Flutter)
- Pub Explorer (could work but could also give the impression of an app to search for bars lol)

I think `pub.dev` is the best. It's simple, it's short, and it's the most accurate.

**Comment by ThinkDigitalSoftware** [comment]
I think there would be an unstated issue with it being called pub.dev since it's unofficial.
Are there any other similarly purposed apps for other package repos that you know of?

**Comment by GroovinChip** [comment]
I'm not aware of any others. We could always put `(unofficial)` after. I've seen that a lot for unofficial client apps.
